### ISSUE TITLE
Should Ignore `mailto:` Links (?)

### ISSUE THREAD

**Issue by salimromadhon** [taufik-nurrohman/f3h#1]
I tried this library and had an error as shown below.

![image](https://user-images.githubusercontent.com/4891012/79453575-10eead00-8014-11ea-922e-5b0ab81258c6.png)

I think it happened because `pushState` API didn't accept that kind of URL (`mailto:mail@example.com`). CMIIW.

**Comment by taufik-nurrohman** [comment]
Okay. I think there will be more URL pattern to be excluded. Including URL prefixed by `javascript:` and `data:`. For now, you can extend the URL exclusion function through the `state.is` property. It&rsquo;s just that the default value isn&rsquo;t accessible unless you instantiate the `F3H` functionality before.

**Method 1:** Requires you to write the whole logic and add your extra URL check there:

~~~ .js
let f3h = new F3H({
        is: source => {
            let target = source.target,
                to = source.getAttribute('href') || source.getAttribute('action');
            return isInternalLinkFunc(to) ||
                0 !== to.search('javascript:') ||
                0 !== to.search('data:') ||
                // etc.
        }
    });
~~~

**Method 2:** To copy the default states data to be applied later with the modified logic (untested):

~~~ .js
let defaultIsFunc = f3h.state.is;

f3.state.is = source => {
    let to = source.getAttribute('href') || source.getAttribute('action');
    return defaultIsFunc(source) ||
        0 !== to.search('javascript:') ||
        0 !== to.search('data:') ||
        // etc.
};
~~~

**Method 3:** Just add `target` attribute with value other than `_self` :wink:

**Comment by salimromadhon** [comment]
I can fix using this method right now:

```
if (F3H !== undefined) {
  var f3h = new F3H;
  (function () {
    var defaultFunc = f3h.state.is;
    f3h.state.is = function (source) {
      var to = (source.getAttribute('href') || source.getAttribute('action'))
      to = to && to.toLowerCase();

      return defaultFunc(source)
        && to.search('javascript:') !== 0
        && to.search('mailto:') !== 0
        && to.search('data:') !== 0;
    };
  })();
}
```

Would love to see update from you. Thanks! 😄

**Comment by taufik-nurrohman** [comment]
It is now possible to get default states through the static `F3H.state` property:

~~~ .js
let defaultIsFunc = F3H.state.is;

F3H.state.is = source => {
    return defaultIsFunc(source) && !source.classList.contains('no-ajax');
};
~~~

URL exclusion for `data:*`, `javascript:*` and `mailto:*` links has been added by default, so no need to use the previous hack. It&rsquo;s just that at least you know how to extend the functionality yourself when some feature requested not accepted by me in the future.
