### ISSUE TITLE
Library breaks a native web feature.

### ISSUE THREAD

**Issue by AustinGil** [taufik-nurrohman/f3h#11]
Hi, I noticed a bug being caused by this library. By default, a browser will allow users to press the CTRL key when clicking on a link, and it will open that link in a new tab. However, when I had this library installed, I noticed that this feature no longer worked.

Is it possible to add a check to any click event handler and only prevent the default behavior if CTRL is not pressed?

**Comment by taufik-nurrohman** [comment]
Thanks for the input. Yes, it should be easy to implement! 👍
