### ISSUE TITLE
Add data-f3h-off functionality

### ISSUE THREAD

**Issue by fransallen** [taufik-nurrohman/f3h#7]
Using `delete this.scripts['SCRIPT_ID'];` can be tricky because we need to define an ID for each element, adding `data-f3h-off` for ignore/deletion may be the solution. What do you think?

**Comment by taufik-nurrohman** [comment]
Let me see if I could solve this by every time carrying the script we want to force reload in the response body. Other than that, I need to consider shorter name or maybe detecting the currently available script attribute such as `defer` or `async` to mark it as a force-reload script.

**Related:** https://github.com/taufik-nurrohman/f3h/blob/v1.0.5/f3h.js#L99&L114

**Comment by taufik-nurrohman** [comment]
`data-f3h` and `f3h` attribute already added as a marker to prevent response body from re-executing the current F3H hooks. But currently I don&rsquo;t determine any standard for the value it has to be. The marker detection only check the existence of that attribute, but doesn&rsquo;t care about the value.

Maybe we can expand it by giving special treatment for those that has an `off` value. As long as it doesn&rsquo;t make it too full featured.

**Comment by taufik-nurrohman** [comment]
For now, you could also do this:

~~~ .js
function onSuccess(response) {
    for (let id in this.scripts) {
        let script = this.scripts[id];
        if (
            script[2] &&
            script[2].src &&
            // Detect by name
            script[2].src.search('/main.js') >= 0
        ) {
            delete this.scripts[id];
            break;
        }
    }
}
~~~

~~~ .js
// Detect by content
if (script[1] && script[1].search('adsbygoogle') => 0) {}
~~~

**Comment by taufik-nurrohman** [comment]
F3H as WordPress plugin acts as an extension that can be opt-in/out from a website with the existing interaction system. In the hope that when the F3H extension is being opt-out, it will not leave code junk like the `data-f3h` attribute in some HTML elements.

I am trying to create a situation where users don&rsquo;t need to set-up special arrangements on their website when they want to use this. However, adding permanent detectors to mark third party codes such as detecting Google AdSense and Google Analytic scripts would make F3H even more inconsistent in the future. It certainly will make F3H depend on those scripts&rsquo; future which is not supposed to happen.

I would consider looking for specific patterns in every third-party codes that are commonly added to WordPress sites to make them an exception without having to change the core code of F3H. And based on the example that I made previously, this is what I have so far:

~~~ .js
function $$(selector, root) {
    return (root || document).querySelector(selector);
}

let f3h = new F3H(true), // Enable cache
    currentBody = document.body,
    currentMetaDescription = $$('meta[content][name="description"]'),
    currentMetaDescriptionOG = $$('meta[content][name="og:description"]'),
    currentRoot = document.documentElement;

f3h.on(200, function(next) {
    let nextBody = next.body,
        nextMetaDescription = $$('meta[content][name="description"]', next),
        nextMetaDescriptionOG = $$('meta[content][name="og:description"]', next),
        nextRoot = next.documentElement;
    // Update document title
    document.title = next.title;
    // Update meta description data if any
    currentMetaDescription &&
    nextMetaDescription &&
    (currentMetaDescription.content = nextMetaDescription.content);
    // Update open-graph meta description data if any
    currentMetaDescriptionOG &&
    nextMetaDescriptionOG &&
    (currentMetaDescriptionOG.content = nextMetaDescriptionOG.content);
    // Update body class names
    currentBody &&
    nextBody &&
    (currentBody.className = nextBody.className);
    // Update root class names (if any)
    currentRoot &&
    nextRoot &&
    (currentRoot.className = nextRoot.className);

    // Other settings goes here. Example:
    // $$('#content').innerHTML = $$('#content', next).innerHTML;

    doAutoDetectScriptsToRefresh(this);
});

function doAutoDetectScriptsToRefresh(base) {
    let id,
        script,
        scripts = base.scripts,
        scriptContent,
        scriptSource;
    for (id in scripts) {
        script = scripts[id];
        scriptContent = script[1] || "";
        scriptSource = script[2].src || "";
        // Ignore case-sensitivity and white-spaces
        scriptContent = scriptContent.toLowerCase().replace(/\s+/g, "");
        // Ignore case-sensitivity, URL protocol, query string and hash
        scriptSource = scriptSource.toLowerCase().replace(/^https?:\/\/|[?&#].*$/g, "");
        if (scriptContent) {
            if (
                // Maybe Google Analytic script
                /\b(_gaq|datalayer|gtag)\b/.test(scriptContent) ||
                // Maybe Google AdSense script
                /\badsbygoogle\b/.test(scriptContent)
            ) {
                delete scripts[id];
            }
        }
        // Remove by source name
        if (scriptSource) {
            if (
                // Maybe Twitter Embed script
                'platform.twitter.com/widgets.js' === scriptSource ||
                // Maybe etc.
                'foo/bar/baz/script-1.js' === scriptSource ||
                'foo/bar/baz/script-2.js' === scriptSource ||
                'foo/bar/baz/script-3.js' === scriptSource ||
                // ...
            ) {
                delete scripts[id];
            }
        }
    }
}
~~~

If you know that some libraries exist, you can also re-initialize it on every AJAX success events:

~~~ .js
// <https://highlightjs.readthedocs.io/en/latest/api.html#inithighlighting>
f3h.on(200, function() {
    'hljs' in window && hljs.initHighlighting();
});

// <https://masonry.desandro.com/methods.html#reloaditems>
let msnry = new Masonry( /* ... */ );
f3h.on(200, function() {
    msnry.reloadItems();
});
~~~

**Comment by taufik-nurrohman** [comment]
I&rsquo;m trying to keep the HTML pages clean from this application requirements. So, I will keep it that way. And as what I have explained in the example above, you don&rsquo;t have to set specific ID to the element you want to force-reload. The application itself will generate the ID randomly for you, and if you want to target specific element based on their source file path or their code snippet representation, then you can utilize the `f3h.scripts` value instead. They&rsquo;re formatted as the way `HTML` class would output the data in Mecha:

``` .js
f3h.scripts = {
    'F3H:1234': ['script', "", {id: 'F3H:1234', src: '/path/to/file-1.js'}],
    'F3H:5678': ['script', "", {id: 'F3H:5678', src: '/path/to/file-2.js'}],
    'custom-ID': ['script', "", {id: 'custom-ID', src: '/path/to/file-3.js'}]
};
```

I would be happy to improve the example. Always check the edit history! :+1:
