### ISSUE TITLE
Add example for jQuery

### ISSUE THREAD

**Issue by fransallen** [taufik-nurrohman/f3h#8]
Due to the integration with [statically-wp](https://github.com/staticallyio/statically-wp), can we provide more examples for jQuery? Just to give an idea so that people can easily apply it to their website, especially when they use jQuery.

**Comment by taufik-nurrohman** [comment]
It&rsquo;s already in the FAQ section: **Can I integrate it with jQuery?**

Do I have to set a live example too for jQuery users?

**Comment by taufik-nurrohman** [comment]
Done.
